name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 09:05 UTC
    - cron: '5 9 * * *'

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          echo "Daily update: $(date -u)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update from GitHub Actions" || echo "No changes to commit"
          git push
